### ISSUE TITLE
微信群二维码失效了

### ISSUE THREAD

**Issue by cielliyuanpeng** [IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL#12]
希望更新呀

**Comment by wkyouc** [comment]
希望更新

**Comment by leiYan1225** [comment]
坐等大佬跟新二维码

**Comment by A-guigui** [comment]
大佬，看见了吗，都在催你，哈哈

**Comment by yshenaw** [comment]
已更新

**Comment by shijiandechendian** [comment]
谁拉我进一下群啊，有尝

**Comment by shijiandechendian** [comment]
谁拉我进一下群啊，有尝

> 希望更新呀

兄弟你进群了吗

**Comment by A-guigui** [comment]
你微信多少，我拉你，无偿




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "shijiandechendian"<notifications@github.com&gt;; 
发送时间: 2020年11月11日(星期三) 晚上7:53
收件人: "IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL"<Paper-with-Code-of-Wireless-communication-Based-on-DL@noreply.github.com&gt;; 
抄送: "加油✊"<1284568211@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL] 微信群二维码失效了 (#12)





 
谁拉我进一下群啊，有尝

**Comment by laplacexie** [comment]
有没有大兄弟or小姐姐也拉我一下，微信/qq:471573313,谢谢啦！

2020-11-12 09:29:40A-guigui <notifications@github.com>写道：

你微信多少，我拉你，无偿




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "shijiandechendian"<notifications@github.com&gt;;
发送时间: 2020年11月11日(星期三) 晚上7:53
收件人: "IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL"<Paper-with-Code-of-Wireless-communication-Based-on-DL@noreply.github.com&gt;;
抄送: "加油✊"<1284568211@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;;
主题: Re: [IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL] 微信群二维码失效了 (#12)






谁拉我进一下群啊，有尝

**Comment by swsky** [comment]
| |
| 有没有可爱的人也拉我一下啊，微信gyao_jyou,谢谢啦！ |
|
|
gyao_jyou@163.com
|
签名由网易邮箱大师定制
在2020年11月23日 16:57，laplacexie<notifications@github.com> 写道：

有没有大兄弟or小姐姐也拉我一下，微信/qq:471573313,谢谢啦！

2020-11-12 09:29:40A-guigui <notifications@github.com>写道：

你微信多少，我拉你，无偿




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "shijiandechendian"<notifications@github.com&gt;;
发送时间: 2020年11月11日(星期三) 晚上7:53
收件人: "IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL"<Paper-with-Code-of-Wireless-communication-Based-on-DL@noreply.github.com&gt;;
抄送: "加油✊"<1284568211@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;;
主题: Re: [IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL] 微信群二维码失效了 (#12)






谁拉我进一下群啊，有尝

**Comment by LiuSjia** [comment]
希望有好心人也拉我一下，微信号：lsj_zxcvbnm
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月23日(星期一) 下午5:14
收件人:&nbsp;"IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL"<Paper-with-Code-of-Wireless-communication-Based-on-DL@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL] 微信群二维码失效了 (#12)





 
 
 
 
 | |
 | 有没有可爱的人也拉我一下啊，微信gyao_jyou,谢谢啦！ |
 |
 |
 gyao_jyou@163.com
 |
 签名由网易邮箱大师定制
 在2020年11月23日 16:57，laplacexie<notifications@github.com&gt; 写道：
 
 有没有大兄弟or小姐姐也拉我一下，微信/qq:471573313,谢谢啦！
 
 2020-11-12 09:29:40A-guigui <notifications@github.com&gt;写道：
 
 你微信多少，我拉你，无偿
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: "shijiandechendian"<notifications@github.com&amp;gt;;
 发送时间: 2020年11月11日(星期三) 晚上7:53
 收件人: "IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL"<Paper-with-Code-of-Wireless-communication-Based-on-DL@noreply.github.com&amp;gt;;
 抄送: "加油✊"<1284568211@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;
 主题: Re: [IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL] 微信群二维码失效了 (#12)
 
 
 
 
 
 
 谁拉我进一下群啊，有尝
