### ISSUE TITLE
微信群

### ISSUE THREAD

**Issue by lmm2000** [IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL#14]
可以麻烦更新一下微信群名片吗？想要进群学习一下深度学习和通信结合的应用~感谢大佬！

**Comment by HuangQiang97** [comment]
你把微信号给我吧，我拉你进群。

**Comment by HuangQiang97** [comment]
> 可以麻烦更新一下微信群名片吗？想要进群学习一下深度学习和通信结合的应用~感谢大佬！

你把微信号给我吧，我拉你进群。

**Comment by ylubg** [comment]
同求拉~ 微信号：807368191
谢谢！~
________________________________
寄件者: HuangQiang97 <notifications@github.com>
寄件日期: 2020年12月23日 上午 11:36
收件者: IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL <Paper-with-Code-of-Wireless-communication-Based-on-DL@noreply.github.com>
副本: Subscribed <subscribed@noreply.github.com>
主旨: Re: [IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL] 微信群 (#14)


你把微信号给我吧，我拉你进群。

―

**Comment by gavin-Ma** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    求拉，微信X2076880775，向大佬学习，谢谢！
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                gavin
                            
                    
                        
                            
                                    gavinma.edu@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年12月23日 11:36，HuangQiang97<notifications@github.com> 写道： 




你把微信号给我吧，我拉你进群。



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lmm2000** [comment]
> 
> 
> > 可以麻烦更新一下微信群名片吗？想要进群学习一下深度学习和通信结合的应用~感谢大佬！
> 
> 你把微信号给我吧，我拉你进群。

好的好的 感谢！微信号：L524yx

**Comment by yokoxue** [comment]
[Image]


________________________________

**Comment by NIIDTzk** [comment]
微信号： wxid_9963509634312

求拉入群













在 2020-12-23 12:52:14，"Ye XUE" <notifications@github.com> 写道：

[Image]


________________________________

**Comment by CharlieWEI2017** [comment]
微信号DC2cnl

求拉进去交流

发自我的 iPhone

**Comment by LeeNUAA** [comment]
求拉微信群学习
微信 lisaaai 谢谢

**Comment by meisme123** [comment]
同求进群
微信 mazer2me 谢谢

LeeNUAA <notifications@github.com> 于2020年12月29日周二 下午8:21写道：

**Comment by CcynthiLu** [comment]
微信号：LXmin_min 求大佬拉进群，非常希望跟大家交流学习！

**Comment by QJSQJS** [comment]
非常抱歉，我也不在群里:(。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;CcynthiLu&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月12日(星期二) 下午4:53
收件人:&nbsp;&quot;IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL&quot;<Paper-with-Code-of-Wireless-communication-Based-on-DL@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL] 微信群 (#14)

**Comment by Bella720** [comment]
求进群! 微信号:  BellaWang-NJ

**Comment by recusant7** [comment]
求进群! 微信号: 1506643318

**Comment by djahdkjqbwfkb1213** [comment]
Vvvvic2 谢谢

**Comment by tian961214** [comment]
求啦！t3656056

**Comment by wsyCUHK** [comment]
> > 可以麻烦更新一下微信群名片吗？想要进群学习一下深度学习和通信结合的应用~感谢大佬！
> 
> 你把微信号给我吧，我拉你进群。

求啦，fadeway

**Comment by djahdkjqbwfkb1213** [comment]
> > 可以麻烦更新一下微信群名片吗？想要进群学习一下深度学习和通信结合的应用~感谢大佬！
> 
> 你把微信号给我吧，我拉你进群。

Vvvvic2 谢谢！

**Comment by tian961214** [comment]
t3656056






------------------

 


田朗

北京邮电大学/研究生/信息与通信工程学院



13940216682

北京


 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by MGML123** [comment]
好的，谢谢你，vx:&nbsp; ZXH15585290242,麻烦您拉我进一下群，谢谢您！



---原始邮件---
发件人: "Shuoyao Wang"<notifications@github.com&gt;
发送时间: 2021年1月28日(周四) 下午2:55
收件人: "IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL"<Paper-with-Code-of-Wireless-communication-Based-on-DL@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL]微信群 (#14)




   
可以麻烦更新一下微信群名片吗？想要进群学习一下深度学习和通信结合的应用~感谢大佬！
  
你把微信号给我吧，我拉你进群。
  
求啦，fadeway

**Comment by MGML123** [comment]
好的，谢谢您！vx ：ZXH15585290242&nbsp; ,麻烦您拉我进一下群，谢谢您！



---原始邮件---
发件人: "tian961214"<notifications@github.com&gt;
发送时间: 2021年1月28日(周四) 下午2:57
收件人: "IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL"<Paper-with-Code-of-Wireless-communication-Based-on-DL@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL] 微信群 (#14)




 t3656056 
 
 
 
 
 
 
 ------------------ 
 
   
 
 
 田朗 
 
 北京邮电大学/研究生/信息与通信工程学院 
 
 
 
 13940216682 
 
 北京 
 
 
   
 
 &amp;nbsp; 
 &amp;nbsp; 
 &amp;nbsp; 
 ------------------&amp;nbsp;Original&amp;nbsp;------------------

**Comment by karokumii** [comment]
同求拉微信群学习 vx：mii5105fall 谢谢！
