### ISSUE TITLE
Wechat Bot

### ISSUE THREAD

**Issue by zhuwenxing** [IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL#24]
![微信图片_20210415232201](https://user-images.githubusercontent.com/12268675/114894720-7650c600-9e41-11eb-8702-a2d95f1b1bee.jpg)

**Comment by zhuwenxing** [comment]
## 智能人工微信机器人
两个微信群均已超过200，不便通过分享群二维码加群，因此建了一个专用的号用于邀请。
所以这个是由人工维护，所以会在一个集中的时间回复，带来不便，请多谅解。

**Comment by IceDRAZ** [comment]
老哥，我想问下有MIMO系统中CSI的数据集嘛

**Comment by recusant7** [comment]
> 老哥，我想问下有MIMO系统中CSI的数据集嘛

https://pan.baidu.com/s/1Ggr6gnsXNwzD4ULbwqCmjA?_at_=1637241963148#list/path=%2F

**Comment by hanghoo** [comment]
你好，请问还可以加群吗？

**Comment by liyiq5** [comment]
邮件已经收到，谢谢，祝好~！

**Comment by Charlie258** [comment]
你好，你的邮件已经收到，谢谢。

**Comment by aiyunhug** [comment]
你好，请问怎么加您的联系方式进群啊，上面那个二维码加不上啊。

**Comment by zhuwenxing** [comment]
> 你好，请问怎么加您的联系方式进群啊，上面那个二维码加不上啊。

可以通过这个群二维码加一下。

![middle_img_v2_b0dba0c9-e83b-461b-a498-2bb21a2373cg](https://user-images.githubusercontent.com/12268675/156929171-db6a95d5-e1ff-4a8f-b71c-b76d2b3e5599.jpg)

**Comment by hj5717** [comment]
请问一下，现在还能进群吗？

**Comment by liyiq5** [comment]
邮件已经收到，谢谢，祝好~！

**Comment by Charlie258** [comment]
你好，你的邮件已经收到，谢谢。

**Comment by Drzhishi** [comment]
还能进群吗

**Comment by liyiq5** [comment]
邮件已经收到，谢谢，祝好~！

**Comment by Charlie258** [comment]
你好，你的邮件已经收到，谢谢。

**Comment by sanlingye** [comment]
您好还可以进群嘛
