### ISSUE TITLE
paper代码路径不正确

### ISSUE THREAD

**Issue by silentsaber** [IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL#31]
Sparsely Connected Neural Network for Massive MIMO Detection 
这篇论文对应的代码链接实际上应该是:
https://github.com/IIT-Lab/MIMO_Detection
但是现在文档里面点进去却是:
https://github.com/NobleLee/MIMO_Detection

**Comment by liyiq5** [comment]
邮件已经收到，谢谢，祝好~！

**Comment by Charlie258** [comment]
你好，你的邮件已经收到，谢谢。

**Comment by zhuwenxing** [comment]
> Sparsely Connected Neural Network for Massive MIMO Detection 这篇论文对应的代码链接实际上应该是: https://github.com/IIT-Lab/MIMO_Detection 但是现在文档里面点进去却是: https://github.com/NobleLee/MIMO_Detection

https://github.com/NobleLee/MIMO_Detection 是原始版本，现在应该是原作者将repo私有化了，所以不可见了，https://github.com/IIT-Lab/MIMO_Detection这个是fork过来的。
