### ISSUE TITLE
Some problems about the relationship between the paper and code

### ISSUE THREAD

**Issue by bugzhu** [IIT-Lab/Paper-with-Code-of-Wireless-communication-Based-on-DL#8]
The main idea about the paper 'Joint Transceiver Optimization for WirelessCommunication PHY with Convolutional NeuralNetwork' is autoencoder. However, the code RadioCNN is just some results about the supervised learning, such as equalization and demodulation. Putting the code and paper together may make some readers misunderstanding and confused, despite the code provider is the third author of the paper.

**Comment by zhuwenxing** [comment]
There may be many reasons for that the code can't match the paper well. Sometimes it can be that the author didn't upload full code or the code is implemented by someone who are not the author.

What I can only ensure is that the code is most related to the paper. And limited by time and knowledge to some fields, I can't check each code repository and correctness is not guaranteed.

If there is a better code repository, I will replace it with the better one. But if there is not, I prefer to reserve it.

By the way, the IEEE version of this paper is [https://ieeexplore.ieee.org/document/8664650](https://ieeexplore.ieee.org/document/8664650) if you can't get access to it,  I can send you a pdf file of it!

**Comment by bugzhu** [comment]
Thanks for your reply. I would be pleased if you would like to send me the
IEEE version. Meanwhile, your awesome paper and code list is
really helpful. Feel sorry for my kind of rude language.
.Thank you in advance.

zhuwenxing <notifications@github.com> 于2019年11月18日周一 下午10:43写道：

**Comment by zhuwenxing** [comment]
Since you did not leave your email, so I create a private repository that includes the pdf file. I invite you as a collaborator, so you can get access to it.

Best Regards!

**Comment by bugzhu** [comment]
Thank you for your reply. I have downloaded the paper.
Best Wishes!

zhuwenxing <notifications@github.com> 于2019年11月19日周二 上午9:35写道：
